<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>abpSourceCode</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\abpSourceCode.Domain\abpSourceCode.Domain.csproj" />
    <ProjectReference Include="..\abpSourceCode.Application.Contracts\abpSourceCode.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="9.2.0" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="9.2.0" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" Version="9.2.0" />
    <PackageReference Include="Volo.Abp.Account.Application" Version="9.2.0" />
    <PackageReference Include="Volo.Abp.Identity.Application" Version="9.2.0" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application" Version="9.2.0" />
  </ItemGroup>

</Project>
